language: node_js
node_js:
  - "stable"

branches:
  only:
    - source

cache:
  directories:
    - node_modules

script:
  - cp .env.prod .env
  - npm run api & npm run generate
  - cp db.json dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  target_branch: master
  on:
    branch: source
