language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  target_branch: master
  on:
    branch: source
